apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-fiber-optic-network-service
  namespace: service-layer
spec:
  destination:
    namespace: fiber-optic
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/tony-fernandez/fiber-optic-network-service.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true